export const types = {
    SEND_REQUEST: "SEND_REQUEST",
    GET_REQUEST: "GET_REQUEST",
    RESET_RANDOM_REQUEST: "RESET_RANDOM_REQUEST",
    DELETE_RANDOM_REQUEST: "DELETE_RANDOM_REQUEST",
    EXPIRE_RANDOM_REQUEST: "EXPIRE_RANDOM_REQUEST",    
    SEND_REQUEST_SUCCESS: "SEND_REQUEST_SUCCESS",
    SEND_REQUEST_ERROR: "SEND_REQUEST_ERROR",

}

